# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xa7a15tcpg236-2I
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Usuario/sumador_NRAO/sumador_NRAO.cache/wt [current_project]
set_property parent.project_path C:/Users/Usuario/sumador_NRAO/sumador_NRAO.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib C:/Users/Usuario/sumador_NRAO/sumador_NRAO.srcs/sources_1/new/mux21.vhd
catch { write_hwdef -file mux21.hwdef }
synth_design -top mux21 -part xa7a15tcpg236-2I
write_checkpoint -noxdef mux21.dcp
catch { report_utilization -file mux21_utilization_synth.rpt -pb mux21_utilization_synth.pb }
